(lang dune 3.16)

(name camic)

(generate_opam_files true)

(source
 (github Liu-Xiangzhi/CAMI))

(authors "Liu Xiangzhi")

(maintainers "Liu Xiangzhi")

(license GPL-v2-or-later-version)

; (documentation https://url/to/documentation)

(package
 (name camic)
 (synopsis "camic <source_path> [source_name] [-o <target>]")
 (description "A compiler that translates C code into CAMI bytecode")
 (depends ocaml dune))
