/*******************************************************************************
 * Copyright (c) 2024. Liu Xiangzhi
 * This file is part of CAMI.
 *
 * CAMI is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software Foundation,
 * either version 2 of the License, or any later version.
 *
 * CAMI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with CAMI.
 * If not, see <https://www.gnu.org/licenses/>.
 ******************************************************************************/

#include <ub.h>

using namespace cami;
using namespace am;

const char* const am::ub_descriptions[] = {
        R"(A "shall" or "shall not" requirement that appears outside of a constraint is violated)",
        R"(A nonempty source file does not end in a new-line character which is not immediately preceded by a backslash character or ends in a partial preprocessing token or comment)",
        R"(Token concatenation produces a character sequence matching the syntax of a universal character name)",
        R"(A program in a hosted environment does not define a function named main using one of the specified forms)",
        R"(The execution of a program contains a data race)",
        R"(A character not in the basic source character set is encountered in a source file, except in an identifier, a character constant, a string literal, a header name, a comment, or a preprocessing token that is never converted to a token)",
        R"(An identifier, comment, string literal, character constant, or header name contains an invalid multibyte character or does not begin and end in the initial shift state)",
        R"(The same identifier has both internal and external linkage in the same translation unit)",
        R"(An object is referred to outside of its lifetime)",
        R"(The value of a pointer to an object whose lifetime has ended is used)",
        R"(The value of an object with automatic storage duration is used while the object has an indeterminate representation)",
        R"(A non-value representation is read by an lvalue expression that does not have character type)",
        R"(A non-value representation is produced by a side effect that modifies any part of the object using an lvalue expression that does not have character type)",
        R"(Two declarations of the same object or function specify types that are not compatible)",
        R"(A program requires the formation of a composite type from a variable length array type whose size is specified by an expression that is not evaluated)",
        R"(Conversion to or from an integer type produces a value outside the range that can be represented)",
        R"(Demotion of one real floating type to another produces a value outside the range that can be represented)",
        R"(An lvalue does not designate an object when evaluated)",
        R"(A non-array lvalue with an incomplete type is used in a context that requires the value of the designated object)",
        R"(An lvalue designating an object of automatic storage duration that could have been declared with the register storage class is used in a context that requires the value of the designated object, but the object is uninitialized)",
        R"(An lvalue having array type is converted to a pointer to the initial element of the array, and the array object has register storage class)",
        R"(An attempt is made to use the value of a void expression, or an implicit or explicit conversion(except to void) is applied to a void expression)",
        R"(Conversion of a pointer to an integer type produces a value outside the range that can be represented)",
        R"(Conversion between two pointer types produces a result that is incorrectly aligned)",
        R"(A pointer is used to call a function whose type is not compatible with the referenced type)",
        R"(An unmatched ’ or " character is encountered on a logical source line during tokenization)",
        R"(A reserved keyword token is used in translation phase 7 or 8 for some purpose other than as a keyword)",
        R"(A universal character name in an identifier does not designate a character whose encoding falls into one of the specified ranges)",
        R"(The initial character of an identifier is a universal character name designating a digit)",
        R"(Two identifiers differ only in nonsignificant characters)",
        R"(The identifier __func__ is explicitly declared)",
        R"(The program attempts to modify a string literal)",
        R"(The characters ’, \, ", //, or /* occur in the sequence between the < and > delimiters, or the characters ’, \, //, or /* occur in the sequence between the " delimiters, in a header name preprocessing token)",
        R"(A side effect on a scalar object is unsequenced relative to either a different side effect on the same scalar object or a value computation using the value of the same scalar object)",
        R"(An exceptional condition occurs during the evaluation of an expression)",
        R"(An object has its stored value accessed other than by an lvalue of an allowable type)",
        R"(A function is defined with a type that is not compatible with the type(of the expression) pointed to by the expression that denotes the called function)",
        R"(A member of an atomic structure or union is accessed)",
        R"(The operand of the unary * operator has an invalid value)",
        R"(A pointer is converted to other than an integer or pointer type)",
        R"(The value of the second operand of the / or % operator is zero)",
        R"(If the quotient a/b is not representable, the behavior of both a/b and a%b)",
        R"(Addition or subtraction of a pointer into, or just beyond, an array object and an integer type produces a result that does not point into, or just beyond, the same array object)",
        R"(Addition or subtraction of a pointer into, or just beyond, an array object and an integer type produces a result that points just beyond the array object and is used as the operand of a unary * operator that is evaluated)",
        R"(Pointers that do not point into, or just beyond, the same array object are subtracted)",
        R"(An array subscript is out of range, even if an object is apparently accessible with the given subscript (as in the lvalue expression a[1][7] given the declaration int a[4][5]))",
        R"(The result of subtracting two pointers is not representable in an object of type ptrdiff_t)",
        R"(An expression is shifted by a negative number or by an amount greater than or equal to the width of the promoted expression)",
        R"(An expression having signed promoted type is left-shifted and either the value of the expression is negative or the result of shifting would not be representable in the promoted type)",
        R"(Pointers that do not point to the same aggregate or union (nor just beyond the same array object) are compared using relational operators)",
        R"(An object is assigned to an inexactly overlapping object or to an exactly overlapping object with incompatible type)",
        R"(An expression that is required to be a an integer constant expression does not have an integer type; has operands that are not integer constants, named constants, compound literal constants, enumeration constants, character constants, predefined constants, sizeof expressions whose results are integer constants, alignof expressions, or immediately-cast floating constants; or contains casts (outside operands to sizeof and alignof operators) other than conversions of arithmetic types to integer types)",
        R"(A constant expression in an initializer is not, or does not evaluate to, one of the following: a named constant, a compound literal constant, an arithmetic constant expression, a null pointer constant, an address constant, or an address constant for a complete object type plus or minus an integer constant expression)",
        R"(An arithmetic constant expression does not have arithmetic type; has operands that are not integer constants, floating constants, enumeration constants, character constants, predefined constants, sizeof expressions whose results are integer constants, or alignof expressions; or contains casts (outside operands to sizeof or alignof operators) other than conversions of arithmetic types to arithmetic types)",
        R"(The value of an object is accessed by an array-subscript [], member-access . or ->, address &, or indirection * operator or a pointer cast in creating an address constant)",
        R"(An identifier for an object is declared with no linkage and the type of the object is incomplete after its declarator, or after its init-declarator if it has an initializer)",
        R"(A function is declared at block scope with an explicit storage-class specifier other than extern)",
        R"(A structure or union is defined without any named members (including those specified indirectly via anonymous structures and unions))",
        R"(An attempt is made to access, or generate a pointer to just past, a flexible array member of a structure when the referenced object provides no elements for that array)",
        R"(When the complete type is needed, an incomplete structure or union type is not completed in the same scope by another declaration of the tag that defines the content)",
        R"(An attempt is made to modify an object defined with a const-qualified type through use of an lvalue with non-const-qualified type)",
        R"(An attempt is made to refer to an object defined with a volatile-qualified type through use of an lvalue with non-volatile-qualified type)",
        R"(The specification of a function type includes any type qualifiers)",
        R"(Two qualified types that are required to be compatible do not have the identically qualified version of a compatible type)",
        R"(An object which has been modified is accessed through a restrict-qualified pointer to a const- qualified type, or through a restrict-qualified pointer and another pointer that are not both based on the same object)",
        R"(A restrict-qualified pointer is assigned a value based on another restricted pointer whose associated block neither began execution before the block associated with this pointer, nor ended before the assignment)",
        R"(A function with external linkage is declared with an inline function specifier, but is not also defined in the same translation unit)",
        R"(A function declared with a _Noreturn function specifier returns to its caller)",
        R"(The definition of an object has an alignment specifier and another declaration of that object has a different alignment specifier)",
        R"(Declarations of an object in different translation units have different alignment specifiers)",
        R"(Two pointer types that are required to be compatible are not identically qualified, or are not pointers to compatible types)",
        R"(The size expression in an array declaration is not a constant expression and evaluates at program execution time to a nonpositive value)",
        R"(In a context requiring two array types to be compatible, they do not have compatible element types, or their size specifiers evaluate to unequal values)",
        R"(A declaration of an array parameter includes the keyword static within the [ and ] and the corresponding argument does not provide access to the first element of an array with at least the specified number of elements)",
        R"(A storage-class specifier or type qualifier modifies the keyword void as a function parameter type list)",
        R"(In a context requiring two function types to be compatible, they do not have compatible return types, or their parameters disagree in use of the ellipsis terminator or the number and type of parameters (after default argument promotion, when there is no parameter type list))",
        R"(A declaration for which a type is inferred contains a pointer, array, or function declarators)",
        R"(A declaration for which a type is inferred contains no or more than one declarators)",
        R"(The value of an unnamed member of a structure or union is used)",
        R"(The initializer for a scalar is neither a single expression nor a single expression enclosed in braces)",
        R"(The initializer for an aggregate or union, other than an array initialized by a string literal, is not a brace-enclosed list of initializers for its elements or members)",
        R"(A function definition that does not have the asserted property is called by a function declaration or a function pointer with a type that has the unsequenced or reproducible attribute)",
        R"(An identifier with external linkage is used, but in the program there does not exist exactly one external definition for the identifier, or the identifier is not used and there exist multiple external definitions for the identifier)",
        R"(A function that accepts a variable number of arguments is defined without a parameter type list that ends with the ellipsis notation)",
        R"(The } that terminates a function is reached, and the value of the function call is used by the caller)",
        R"(An identifier for an object with internal linkage and an incomplete type is declared with a tentative definition)",
        R"(A non-directive preprocessing directive is executed)",
        R"(The token defined is generated during the expansion of a #if or #elif preprocessing directive, or the use of the defined unary operator does not match one of the two specified forms prior to macro replacement)",
        R"(The #include preprocessing directive that results after expansion does not match one of the two header name forms)",
        R"(The character sequence in an #include preprocessing directive does not start with a letter)",
        R"(There are sequences of preprocessing tokens within the list of macro arguments that would otherwise act as preprocessing directives)",
        R"(The result of the preprocessing operator # is not a valid character string literal)",
        R"(The result of the preprocessing operator ## is not a valid preprocessing token)",
        R"(The #line preprocessing directive that results after expansion does not match one of the two well-defined forms, or its digit sequence specifies zero or a number greater than 2147483647)",
        R"(A non-STDC #pragma preprocessing directive that is documented as causing translation failure or some other form of undefined behavior is encountered)",
        R"(A #pragma STDC preprocessing directive does not match one of the well-defined forms)",
        R"(The name of a predefined macro, or the identifier defined, is the subject of a #define or #undef preprocessing directive)",
        R"(An attempt is made to copy an object to an overlapping object by use of a library function, other than as explicitly allowed (e.g., memmove))",
        R"(A file with the same name as one of the standard headers, not provided as part of the implementation, is placed in any of the standard places that are searched for included source files)",
        R"(A header is included within an external declaration or definition)",
        R"(A function, object, type, or macro that is specified as being declared or defined by some standard header is used before any header that declares or defines it is included)",
        R"(A standard header is included while a macro is defined with the same name as a keyword)",
        R"(The program attempts to declare a library function itself, rather than via a standard header, but the declaration does not have external linkage)",
        R"(The program declares or defines a reserved identifier, other than as allowed by 7.1.4)",
        R"(The program removes the definition of a macro whose name begins with an underscore and either an uppercase letter or another underscore)",
        R"(An argument to a library function has an invalid value or a type not expected by a function with a variable number of arguments)",
        R"(The pointer passed to a library function array parameter does not have a value such that all address computations and object accesses are valid)",
        R"(The macro definition of assert is suppressed to access an actual function)",
        R"(The argument to the assert macro does not have a scalar type)",
        R"(The CX_LIMITED_RANGE, FENV_ACCESS, or FP_CONTRACT pragma is used in any context other than outside all external declarations or preceding all explicit declarations and statements inside a compound statement)",
        R"(The value of an argument to a character handling function is neither equal to the value of EOF nor representable as an unsigned char)",
        R"(A macro definition of errno is suppressed to access an actual object, or the program defines an identifier with the name errno)",
        R"(Part of the program tests floating-point status flags, sets floating-point control modes, or runs under non-default mode settings, but was translated with the state for the FENV_ACCESS pragma "off")",
        R"(The exception-mask argument for one of the functions that provide access to the floating-point status flags has a nonzero value not obtained by bitwise OR of the floating-point exception macros)",
        R"(The fesetexceptflag function is used to set floating-point status flags that were not specified in the call to the fegetexceptflag function that provided the value of the corresponding fexcept_t object)",
        R"(The argument to fesetenv or feupdateenv is neither an object set by a call to fegetenv or feholdexcept, nor is it an environment macro)",
        R"(The value of the result of an integer arithmetic or conversion function cannot be represented)",
        R"(The program modifies the string pointed to by the value returned by the setlocale function)",
        R"(A pointer returned by the setlocale function is used after a subsequent call to the function, or after the calling thread has exited)",
        R"(The program modifies the structure pointed to by the value returned by the localeconv function)",
        R"(A macro definition of math_errhandling is suppressed or the program defines an identifier with the name math_errhandling)",
        R"(An argument to a floating-point classification or comparison macro is not of real floating type)",
        R"(A macro definition of setjmp is suppressed to access an actual function, or the program defines an external identifier with the name setjmp)",
        R"(An invocation of the setjmp macro occurs other than in an allowed context)",
        R"(The longjmp function is invoked to restore a nonexistent environment)",
        R"(After a longjmp, there is an attempt to access the value of an object of automatic storage dura- tion that does not have volatile-qualified type, local to the function containing the invocation of the corresponding setjmp macro, that was changed between the setjmp invocation and longjmp call)",
        R"(The program specifies an invalid pointer to a signal handler function)",
        R"(A signal handler returns when the signal corresponded to a computational exception)",
        R"(A signal handler called in response to SIGFPE, SIGILL, SIGSEGV, or any other implementation- defined value corresponding to a computational exception returns)",
        R"(A signal occurs as the result of calling the abort or raise function, and the signal handler calls the raise function)",
        R"(A signal occurs other than as the result of calling the abort or raise function, and the signal handler refers to an object with static or thread storage duration that is not a lock-free atomic object other than by assigning a value to an object declared as volatile sig_atomic_t, or calls any function in the standard library other than the abort function, the _Exit function, the quick_exit function, the functions in <stdatomic.h> (except where explicitly stated otherwise) when the atomic arguments are lock-free, the atomic_is_lock_free function with any atomic argument, or the signal function (for the same signal number))",
        R"(The value of errno is referred to after a signal occurred other than as the result of calling the abort or raise function and the corresponding signal handler obtained a SIG_ERR return from a call to the signal function)",
        R"(A signal is generated by an asynchronous signal handler)",
        R"(The signal function is used in a multi-threaded program)",
        R"(A function with a variable number of arguments attempts to access its varying arguments other than through a properly declared and initialized va_list object, or before the va_start macro is invoked)",
        R"(The macro va_arg is invoked using the parameter ap that was passed to a function that invoked the macro va_arg with the same parameter)",
        R"(A macro definition of va_start, va_arg, va_copy, or va_end is suppressed to access an actual function, or the program defines an external identifier with the name va_copy or va_end)",
        R"(The va_start or va_copy macro is invoked without a corresponding invocation of the va_end macro in the same function, or vice versa)",
        R"(The type parameter to the va_arg macro is not such that a pointer to an object of that type can be obtained simply by postfixing a *)",
        R"(The va_arg macro is invoked when there is no actual next argument, or with a specified type that is not compatible with the promoted type of the actual next argument, with certain exceptions)",
        R"(Using a null pointer constant in form of an integer expression as an argument to a ... function and then interpreting it as a void* or char*)",
        R"(The va_copy or va_start macro is called to initialize a va_list that was previously initialized by either macro without an intervening invocation of the va_end macro for the same va_list)",
        R"(The macro definition of a generic function is suppressed to access an actual function (7.17.1, 7.18))",
        R"(The type parameter of an offsetof macro defines a new type)",
        R"(When program execution reaches an unreachable() macro call)",
        R"(Arbitrarily copying or changing the bytes of or copying from a non-null pointer into a nullptr_t object and then reading that object)",
        R"(The member-designator parameter of an offsetof macro is an invalid right operand of the operator for the type parameter, or designates a bit-field)",
        R"(The argument in an instance of one of the integer-constant macros is not a decimal, octal, or hexadecimal constant, or it has a value that exceeds the limits for the corresponding type)",
        R"(A byte input/output function is applied to a wide-oriented stream, or a wide character input/output function is applied to a byte-oriented stream)",
        R"(Use is made of any portion of a file beyond the most recent wide character written to a wide-oriented stream)",
        R"(The value of a pointer to a FILE object is used after the associated file is closed)",
        R"(The stream for the fflush function points to an input stream or to an update stream in which the most recent operation was input)",
        R"(The string pointed to by the mode argument in a call to the fopen function does not exactly match one of the specified character sequences)",
        R"(An output operation on an update stream is followed by an input operation without an intervening call to the fflush function or a file positioning function, or an input operation on an update stream is followed by an output operation with an intervening call to a file positioning function)",
        R"(An attempt is made to use the contents of the array that was supplied in a call to the setvbuf function)",
        R"(There are insufficient arguments for the format in a call to one of the formatted input/output functions, or an argument does not have an appropriate type (7.23.6.1, 7.23.6.2, 7.31.2.1, 7.31.2.2))",
        R"(The format in a call to one of the formatted input/output functions or to the strftime or wcsftime function is not a valid multibyte character sequence that begins and ends in its initial shift state)",
        R"(In a call to one of the formatted output functions, a precision appears with a conversion specifier other than those described)",
        R"(A conversion specification for a formatted output function uses an asterisk to denote an argument-supplied field width or precision, but the corresponding argument is not provided)",
        R"(A conversion specification for a formatted output function uses a # or 0 flag with a conversion specifier other than those described)",
        R"(A conversion specification for one of the formatted input/output functions uses a length modifier with a conversion specifier other than those described (7.23.6.1, 7.23.6.2, 7.31.2.1, 7.31.2.2))",
        R"(An s conversion specifier is encountered by one of the formatted output functions, and the argument is missing the null terminator (unless a precision is specified that does not require null termination))",
        R"(An n conversion specification for one of the formatted input/output functions includes any flags, an assignment-suppressing character, a field width, or a precision (7.23.6.1, 7.23.6.2, 7.31.2.1, 7.31.2.2))",
        R"(A % conversion specifier is encountered by one of the formatted input/output functions, but the complete conversion specification is not exactly %%)",
        R"(An invalid conversion specification is found in the format for one of the formatted input/out- put functions, or the strftime or wcsftime function (7.23.6.1, 7.23.6.2, 7.29.3.5, 7.31.2.1, 7.31.2.2, 7.31.5.1))",
        R"(The number of characters or wide characters transmitted by a formatted output function (or written to an array, or that would have been written to an array) is greater than INT_MAX)",
        R"(The number of input items assigned by a formatted input function is greater than INT_MAX)",
        R"(The result of a conversion by one of the formatted input functions cannot be represented in the corresponding object, or the receiving object does not have an appropriate type (7.23.6.2, 7.31.2.2))",
        R"(A c, s, or [ conversion specifier is encountered by one of the formatted input functions, and the array pointed to by the corresponding argument is not large enough to accept the input sequence (and a null terminator if the conversion specifier is s or [))",
        R"(A c, s, or [ conversion specifier with an l qualifier is encountered by one of the formatted input functions, but the input is not a valid multibyte character sequence that begins in the initial shift state)",
        R"(The input item for a %p conversion by one of the formatted input functions is not a value converted earlier during the same program execution)",
        R"(The vfprintf, vfscanf, vprintf, vscanf, vsnprintf, vsprintf, vsscanf, vfwprintf, vfwscanf, vswprintf, vswscanf, vwprintf, or vwscanf function is called with an improperly initialized va_list argument, or the argument is used (other than in an invocation of va_end) after the function returns (7.23.6.8, 7.23.6.9, 7.23.6.10, 7.23.6.11, 7.23.6.12, 7.23.6.13, 7.23.6.14, 7.31.2.5, 7.31.2.6, 7.31.2.7, 7.31.2.8, 7.31.2.9, 7.31.2.10))",
        R"(The contents of the array supplied in a call to the fgets or fgetws function are used after a read error occurred)",
        R"(The file position indicator for a binary stream is used after a call to the ungetc function where its value was zero before the call)",
        R"(The file position indicator for a stream is used after an error occurred during a call to the fread or fwrite function)",
        R"(A partial element read by a call to the fread function is used)",
        R"(The fseek function is called for a text stream with a nonzero offset and either the offset was not returned by a previous successful call to the ftell function on a stream associated with the same file or whence is not SEEK_SET)",
        R"(The fsetpos function is called to set a position that was not returned by a previous successful call to the fgetpos function on a stream associated with the same file)",
        R"(A non-null pointer returned by a call to the calloc, malloc, realloc, or aligned_alloc function with a zero requested size is used to access an object)",
        R"(The value of a pointer that refers to space deallocated by a call to the free or realloc function is used)",
        R"(The pointer argument to the free or realloc function does not match a pointer earlier returned by a memory management function, or the space has been deallocated by a call to free or realloc)",
        R"(The value of the object allocated by the malloc function is used)",
        R"(The values of any bytes in a new object allocated by the realloc function beyond the size of the old object are used)",
        R"(The program calls the exit or quick_exit function more than once, or calls both functions)",
        R"(During the call to a function registered with the atexit or at_quick_exit function, a call is made to the longjmp function that would terminate the call to the registered function (7.24.4.4, 7.24.4.7))",
        R"(The string set up by the getenv or strerror function is modified by the program (7.24.4.6, 7.26.6.3))",
        R"(A signal is raised while the quick_exit function is executing)",
        R"(A command is executed through the system function in a way that is documented as causing termination or some other form of undefined behavior)",
        R"(A searching or sorting utility function is called with an invalid pointer argument, even if the number of elements is zero)",
        R"(The comparison function called by a searching or sorting utility function alters the contents of the array being searched or sorted, or returns ordering values inconsistently)",
        R"(The array being searched by the bsearch function does not have its elements in proper order)",
        R"(The current conversion state is used by a multibyte/wide character conversion function after changing the LC_CTYPE category)",
        R"(A string or wide string utility function is instructed to access an array beyond the end of an object)",
        R"(A string or wide string utility function is called with an invalid pointer argument, even if the length is zero)",
        R"(The contents of the destination array are used after a call to the strxfrm, strftime, wcsxfrm, or wcsftime function in which the specified length was too small to hold the entire null- terminated result)",
        R"(A sequence of calls of the strtok function is made from different threads)",
        R"(The first argument in the very first call to the strtok or wcstok is a null pointer (7.26.5.9, 7.31.4.6.7))",
        R"(A pointer returned by the strerror function is used after a subsequent call to the function, or after the calling thread has exited)",
        R"(The type of an argument to a type-generic macro is not compatible with the type of the corresponding parameter of the selected function)",
        R"(Arguments for generic parameters of a type-generic macro are such that some argument has a corresponding real type that is of standard floating type and another argument is of decimal floating type)",
        R"(Arguments for generic parameters of a type-generic macro are such that neither <math.h> and <complex.h> define a function whose generic parameters have the determined corresponding real type)",
        R"(A complex argument is supplied for a generic parameter of a type-generic macro that has no corresponding complex function)",
        R"(A decimal floating argument is supplied for a generic parameter of a type-generic macro that expects a complex argument)",
        R"(A standard floating or complex argument is supplied for a generic parameter of a type-generic macro that expects a decimal floating type argument)",
        R"(A non-recursive mutex passed to mtx_lock is locked by the calling thread)",
        R"(The mutex passed to mtx_timedlock does not support timeout)",
        R"(The mutex passed to mtx_unlock is not locked by the calling thread)",
        R"(The thread passed to thrd_detach or thrd_join was previously detached or joined with another thread)",
        R"(The tss_create function is called from within a destructor)",
        R"(The key passed to tss_delete, tss_get, or tss_set was not returned by a call to tss_create before the thread commenced executing destructors)",
        R"(An attempt is made to access the pointer returned by the time conversion functions after the thread that originally called the function to obtain it has exited)",
        R"(At least one member of the broken-down time passed to asctime contains a value outside its normal range, or the calculated year exceeds four digits or is less than the year 1000)",
        R"(The argument corresponding to an s specifier without an l qualifier in a call to the fwprintf function does not point to a valid multibyte character sequence that begins in the initial shift state)",
        R"(In a call to the wcstok function, the object pointed to by ptr does not have the value stored by the previous call for the same wide string)",
        R"(An mbstate_t object is used inappropriately)",
        R"(The value of an argument of type wint_t to a wide character classification or case mapping function is neither equal to the value of WEOF nor representable as a wchar_t)",
        R"(The iswctype function is called using a different LC_CTYPE category from the one in effect for the call to the wctype function that returned the description)",
        R"(The towctrans function is called using a different LC_CTYPE category from the one in effect for the call to the wctrans function that returned the description)",
};