(* 4 Floating_point subject sequence *)
(* 4.1 NaN char sequence *)
n_char_sequence
    = digit
    | nondigit
    | n_char_sequence, digit
    | n_char_sequence, nondigit;

(* 4.2 NaN wchar_t sequence *)
n_wchar_sequence
    = digit
    | nondigit
    | n_wchar_sequence, digit
    | n_wchar_sequence, nondigit;

(* 5 Decimal floating_point subject sequence *)
(* 5.1 NaN decimal char sequence *)
d_char_sequence
    = digit
    | nondigit
    | d_char_sequence, digit
    | d_char_sequence, nondigit;

(* 5.2 NaN decimal wchar_t sequence *)
d_wchar_sequence
    = digit
    | nondigit
    | d_wchar_sequence, digit
    | d_wchar_sequence, nondigit;
