(* 3 Preprocessing directives *)
preprocessing_file
    = [ group ];

group
    = group_part
    | group, group_part;

group_part
    = if_section
    | control_line
    | text_line
    | '#', non_directive;

if_section
    = if_group, [ elif_groups ], [ else_group ], endif_line;

if_group
    = '#', 'if', constant_expression, new_line, [ group ]
    | '#', 'ifdef', identifier, new_line, [ group ]
    | '#', 'ifndef', identifier, new_line, [ group ];

elif_groups
    = elif_group
    | elif_groups, elif_group;

elif_group
    = '#', 'elif', constant_expression, new_line, [ group ]
    | '#', 'elifdef', identifier, new_line, [ group ]
    | '#', 'elifndef', identifier, new_line, [ group ];

else_group
    = '#', 'else', new_line, [ group ];

endif_line
    = '#', 'endif', new_line;

control_line
    = '#', 'include', pp_tokens, new_line
    | '#', 'embed', pp_tokens, new_line
    | '#', 'define', identifier, replacement_list, new_line
    | '#', 'define', identifier, lparen, [ identifier_list ], ')', replacement_list, new_line
    | '#', 'define', identifier, lparen, '...', ')', replacement_list, new_line
    | '#', 'define', identifier, lparen, identifier_list, ',', '...', ')', replacement_list, new_line
    | '#', 'undef', identifier, new_line
    | '#', 'line', pp_tokens, new_line
    | '#', 'error', [ pp_tokens ], new_line
    | '#', 'warning', [ pp_tokens ], new_line
    | '#', 'pragma', [ pp_tokens ], new_line
    | '#', new_line;

text_line
    = [ pp_tokens ], new_line;

non_directive
    = pp_tokens, new_line;

lparen
    = ? a '(' character not immediately preceded by white space ?;

replacement_list
    = [ pp_tokens ];

pp_tokens
    = preprocessing_token
    | pp_tokens, preprocessing_token;

new_line
    = ? the new_line character ?;

identifier_list
    = identifier
    | identifier_list, ',', identifier;

pp_parameter
    = pp_parameter_name, [ pp_parameter_clause ];

pp_parameter_name
    = pp_standard_parameter
    | pp_prefixed_parameter;

pp_standard_parameter
    = identifier;

pp_prefixed_parameter
    = identifier, '::', identifier;

pp_parameter_clause
    = '(', [ pp_balanced_token_sequence ], ')';

pp_balanced_token_sequence
    = pp_balanced_token
    | pp_balanced_token_sequence, pp_balanced_token;

pp_balanced_token
    = '(', [ pp_balanced_token_sequence ], ')'
    | '[', [ pp_balanced_token_sequence ], ']'
    | '{', [ pp_balanced_token_sequence ], '}'
    | ? any pp_token other than a parenthesis , a bracket , or a brace ?;

embed_parameter_sequence
    = pp_parameter
    | embed_parameter_sequence, pp_parameter;

defined_macro_expression
    = 'defined', identifier
    | 'defined', '(', identifier, ')';

h_preprocessing_token
    = ? any preprocessing_token other than > ?;

h_pp_tokens
    = h_preprocessing_token
    | h_pp_tokens, h_preprocessing_token;

header_name_tokens
    = string_literal
    | '<', h_pp_tokens, '>';

has_include_expression
    = '__has_include', '(', header_name, ')'
    | '__has_include', '(', header_name_tokens, ')';

has_embed_expression
    = '__has_embed', '(', header_name, [ embed_parameter_sequence ], ')'
    | '__has_embed', '(', header_name_tokens, [ pp_balanced_token_sequence ], ')';

has_c_attribute_express
    = '__has_c_attribute', '(', pp_tokens, ')';

va_opt_replacement
    = '__VA_OPT__', '(', [ pp_tokens ], ')';

standard_pragma
    = '#', 'pragma', 'STDC', 'FP_CONTRACT', on_off_switch
    | '#', 'pragma', 'STDC', 'FENV_ACCESS', on_off_switch
    | '#', 'pragma', 'STDC', 'FENV_DEC_ROUND', dec_direction
    | '#', 'pragma', 'STDC', 'FENV_ROUND', direction
    | '#', 'pragma', 'STDC', 'CX_LIMITED_RANGE', on_off_switch;

on_off_switch
    = 'ON'
    | 'OFF'
    | 'DEFAULT';

direction
    = 'FE_DOWNWARD'
    | 'FE_TONEAREST'
    | 'FE_TONEARESTFROMZERO'
    | 'FE_TOWARDZERO'
    | 'FE_UPWARD'
    | 'FE_DYNAMIC';

dec_direction
    = 'FE_DEC_DOWNWARD'
    | 'FE_DEC_TONEAREST'
    | 'FE_DEC_TONEARESTFROMZERO'
    | 'FE_DEC_TOWARDZERO'
    | 'FE_DEC_UPWARD'
    | 'FE_DEC_DYNAMIC';
